version: 2
 ethernets:
  enp0s1:
   dhcp4: false
   addresses: [ 192.168.122.40/24 ]
   gateway4: 192.168.122.1
   gateway6: fc00::12
   nameservers:
    addresses: [ 192.168.1.19, 192.168.1.22 ]
    search: [harrison.local]